# -*- coding: utf-8 -*-
"""JobDB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S5-YNE-nrP4LILWqQ0qzIS_dyOs3rpik
"""

!pip install selenium
!apt-get update
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin
import pandas as pd
import sys
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')

from selenium import webdriver
from selenium.webdriver.common.by import By
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
driver = webdriver.Chrome('chromedriver',chrome_options=chrome_options)

URL = 'https://www.jobthai.com/%E0%B8%AB%E0%B8%B2%E0%B8%87%E0%B8%B2%E0%B8%99/%E0%B8%87%E0%B8%B2%E0%B8%99%E0%B8%84%E0%B8%AD%E0%B8%A1%E0%B8%9E%E0%B8%B4%E0%B8%A7%E0%B9%80%E0%B8%95%E0%B8%AD%E0%B8%A3%E0%B9%8C-it-%E0%B9%82%E0%B8%9B%E0%B8%A3%E0%B9%81%E0%B8%81%E0%B8%A3%E0%B8%A1%E0%B9%80%E0%B8%A1%E0%B8%AD%E0%B8%A3%E0%B9%8C/1'
driver.get(URL)

date = driver.find_elements(By.CLASS_NAME, "msklqa-6")
date[1].text

all_date = [i.text for i in date]
all_date

job = driver.find_elements(By.CLASS_NAME, "frNqfE")
job[0].text

all_job = [i.text for i in job]
all_job

company = driver.find_elements(By.CLASS_NAME, "gWWIiL")
company[0].text

all_company = [i.text for i in company]
all_company

location = driver.find_elements(By.CLASS_NAME, "ijtKqG")
location[0].text

all_location = [i.text for i in location]
all_location

salary = driver.find_elements(By.ID, "salary-text")
salary[0].text

all_salary = [i.text for i in salary]
all_salary

page = driver.find_element(By.XPATH, "//a[@id='next-button']")
page.click()
sleep(5)

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
WebDriverWait(browser, 20).until(EC.presence_of_element_located((By.XPATH, "//a[@id='next-button']"))).click()

df = pd.DataFrame(zip(all_date,all_job,all_company,all_location,all_salary), columns = ['วันที่','ตำแหน่งงาน','บริษัท','สถานที่','เงินเดือน'])
df

df.to_json('file.json', orient = 'split', compression = 'infer', index = 'true',force_ascii=0)
driver.close();