# -*- coding: utf-8 -*-
"""Evspec.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c3nycux7tHQpq8EHOk3pbVnVwiVMr9GN
"""

!pip install selenium
!apt-get update
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin
import pandas as pd
import sys
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')

from selenium import webdriver
from selenium.webdriver.common.by import By
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
driver = webdriver.Chrome('chromedriver',chrome_options=chrome_options)

URL = 'https://www.skooldio.com/browse?type=COURSE'
driver.get(URL)

data = driver.page_source
data

Course_Name = driver.find_element(By.CLASS_NAME, "cvepBP")
Course_Names = [i.text for i in Course_Name]

Course_Link = driver.find_elements(By.LINK_TEXT, "kUXLSl")
Course_Links = [i.text for i in Course_Link]

date_comment	= driver.find_element(By.CLASS_NAME, "jylndx")
date_comments = [i.text for i in date_comment]

star = driver.find_element(By.CLASS_NAME, "MuiRating-readOnly")
stars = [i.text for i in star]

review = driver.find_element(By.CLASS_NAME, "eZssoC")
reviews = [i.text for i in review]

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, "//a[@id='next-button']"))).click()

df = pd.DataFrame(zip(Course_Names,Course_Links,date_comments,stars,reviews), columns = ['Course Name','Course Link','date_comment','star','review'])
df

df
df.to_json('file.json', orient = 'split', compression = 'infer', index = 'true',force_ascii=0)

driver.close();